Update Dockerfile
Committing file

diff --git a/.docker/firefox/Dockerfile b/.docker/firefox/Dockerfile
--- a/.docker/firefox/Dockerfile
+++ b/.docker/firefox/Dockerfile
@@ -1,32 +1,34 @@
+# Base image
 ARG BASE_IMAGE=m1k1o/neko:base
 FROM $BASE_IMAGE
 
-ARG SRC_URL="https://download.mozilla.org/?product=firefox-latest&os=linux64&lang=en-US"
+# Copy local Firefox archive
+COPY firefox-setup.tar.bz2 /tmp/firefox-setup.tar.bz2
 
-#
-# install firefox
-RUN set -eux; apt-get update; \
-    apt-get install -y --no-install-recommends openbox \
-    xz-utils bzip2 libgtk-3-0 libdbus-glib-1-2; \
-    #
-    # fetch latest release
-    wget -O /tmp/firefox-setup.tar.bz2 "${SRC_URL}"; \
-    mkdir /usr/lib/firefox; \
-    tar -xjf /tmp/firefox-setup.tar.bz2 -C /usr/lib; \
+# Install Firefox and dependencies
+RUN set -eux; \
+    apt-get update; \
+    apt-get install -y --no-install-recommends openbox bzip2 libgtk-3-0 libdbus-glib-1-2; \
+    \
+    # Verify the archive
+    bzip2 -t /tmp/firefox-setup.tar.bz2 || { echo "Error: Firefox archive is invalid"; exit 1; }; \
+    \
+    # Extract Firefox
+    mkdir -p /usr/lib/firefox; \
+    tar -xjf /tmp/firefox-setup.tar.bz2 -C /usr/lib/firefox --strip-components=1; \
     rm -f /tmp/firefox-setup.tar.bz2; \
     ln -s /usr/lib/firefox/firefox /usr/bin/firefox; \
-    #
-    # create a profile directory
+    \
+    # Create Firefox profile directory
     mkdir -p /home/neko/.mozilla/firefox/profile.default/extensions; \
     chown -R neko:neko /home/neko/.mozilla/firefox/profile.default; \
-    #
-    # clean up
-    apt-get --purge autoremove -y xz-utils bzip2; \
+    \
+    # Clean up
+    apt-get --purge autoremove -y bzip2; \
     apt-get clean -y; \
     rm -rf /var/lib/apt/lists/* /var/cache/apt/*
 
-#
-# copy configuation files
+# Copy configuration files
 COPY supervisord.conf /etc/neko/supervisord/firefox.conf
 COPY neko.js /usr/lib/firefox/mozilla.cfg
 COPY autoconfig.js /usr/lib/firefox/defaults/pref/autoconfig.js
